- type: department
  id: BlueShield
  name: department-BlueShield
  description: department-BlueShield-description
  color: "#339FFF"
  roles:
  - BlueShieldOfficer

- type: department
  id: LegalDepartment
  name: department-LegalDepartment
  description: department-LegalDepartment-description
  color: "#5c4a41"
  weight: 10
  roles:
  - IAA
  - Lawyer

- type: department
  id: CrimsonLily
  name: department-CrimsonLily
  description: department-CrimsonLily-description
  color: "#990000"
  roles:
  - AgentCrimsonLily
  - SpIFD
  # - OperativeCrimsonLily

- type: department
  id: SpCentCommon
  name: department-SpCentCommon
  description: department-SpCentCommon-description
  color: "#00842e"
  roles:
  - SpNanoTrasenRepresentative
  - SpCCO
  # - SpICC
