- type: job
  id: AgentCrimsonLily
  name: job-name-crimson-lily-agent
  description: job-description-finance-defend
  playTimeTracker: JobAgentCrimsonLily
  setPreference: true
  startingGear: AgentCrimsonLilyStationGear
  icon: "JobIconAgentCrimsonLily"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-crimson-lily-centcom
  canBeAntag: false
  whitelisted: true
  chatHighlight: CommandChatHighlight
  accessGroups:
  - StationAccessAgentCrimsonLily
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: CommandStaff

- type: startingGear
  id: AgentCrimsonLilyStationGear
  equipment:
    id: AgentCrimsonLilyPDA
    ears: ClothingHeadsetAgentCrimsonLily
    belt: ClothingBeltSecurityFilled
    pocket1: StationACLWeaponPulsePistol
    pocket2: StationACLWeaponPulsePistol
  storage:
    back:
    - BoxSurvivalSecurity
    - BoxAgentCrimsonLily
    - Flash
    - TrackingImplanter
    - LightImplanter
    - HandheldSpCargoOrders
    - ClothingOuterArmorSecurity
    - SpCentComAccessConfigurator
    - SecurityWhistle
    - TelescopicBaton
# Top set

- type: entity
  parent: ClothingHeadHatBeret
  id: ClothingHeadHatBeretAgentCrimsonLily
  name: crimson lily agent beret
  suffix: ACL
  description: Stylish, fashionable and respectable.
  components:
  - type: Sprite
    sprite: DarkStation/MainGame/Clothing/Head/Hats/Berets/crimson_lily.rsi
  - type: Clothing
    sprite: DarkStation/MainGame/Clothing/Head/Hats/Berets/crimson_lily.rsi

- type: entity
  parent: ClothingHeadsetAlt
  id: ClothingHeadsetAgentCrimsonLily
  name: crimson lily agent headset
  suffix: ACL
  description: The crimson lily headset allows you to communicate through the many available channels to further demand money from stations.
  components:
  - type: ContainerFill
    containers:
      key_slots:
      - EncryptionKeyCrimsonLily
      - EncryptionKeyStationMaster
  - type: Sprite
    sprite: DarkStation/MainGame/Clothing/Ears/Headsets/crimson_lily.rsi
  - type: Clothing
    sprite: DarkStation/MainGame/Clothing/Ears/Headsets/crimson_lily.rsi

- type: entity
  parent: ClothingEyesGlassesSecurity
  id: ClothingEyesGlassesAgentCrimsonLily
  name: crimson lily agent glasses
  suffix: ACL
  description: Special agent crimson lily glasses that allow you to monitor the status of individuals before him.
  components:
  - type: EyeProtection
  - type: ShowHealthIcons

# Accessories

- type: entity
  parent: ClothingHandsGlovesPowerglove
  id: ClothingHandsGlovesPowergloveAgentCrimsonLily
  name: crimson lily agent power gloves
  description: Agent crimson lily specialized power gloves for productive activities.
  components:
  - type: Insulated
  - type: Sprite
    sprite: DarkStation/MainGame/Clothing/Hands/Gloves/crimson_lily.rsi
  - type: Clothing
    sprite: DarkStation/MainGame/Clothing/Hands/Gloves/crimson_lily.rsi

- type: entity
  parent: ClothingShoesBootsMagSyndie
  id: ClothingShoesBootsMagAgentCrimsonLily
  name: crimson lily agent magboots
  suffix: ACL
  description: With magnetic boots like these, there's little to fear.

# Uniform
- type: entity
  parent: ClothingUniformBase
  id: ClothingUniformJumpsuitAgentCrimsonLily
  name: crimson lily agent uniform
  suffix: ACL
  description: You feel safe around him. But you don't feel safe with your money...
  components:
  - type: Sprite
    sprite: DarkStation/MainGame/Clothing/Uniforms/Jumpsuit/crimson_lily.rsi
  - type: Clothing
    sprite: DarkStation/MainGame/Clothing/Uniforms/Jumpsuit/crimson_lily.rsi
  - type: Armor
    modifiers:
      coefficients:
        Blunt: 0.8
        Slash: 0.8
        Piercing: 0.8
      securePartTypes:
        Leg: 0.8
        Arm: 0.8

- type: entity
  parent: ClothingNeckBase
  id: ClothingNeckCloakGoliathCloakAgentCrimsonLily
  name: crimson lily agent cloak
  suffix: ACL
  description: Goliath's cloak, made from the hide of a hardy fauna from a distant planet. However, over time, its protective properties have weakened.
  components:
  - type: Sprite
    sprite: DarkStation/MainGame/Clothing/Neck/Mantles/crimson_lily.rsi
  - type: ContainerContainer
    containers:
      toggleable-clothing: !type:ContainerSlot { }

# Hardsuit

- type: entity
  parent: ClothingOuterHardsuitSecurity
  id: ClothingOuterHardsuitAgentCrimsonLily
  name: crimson lily agent hardsuit
  description: With a suit like that, you could sell another man's station.
  components:
  - type: Sprite
    sprite: DarkStation/MainGame/Clothing/OuterClothing/Hardsuits/CrimsonLily/scaf.rsi
  - type: Clothing
    sprite: DarkStation/MainGame/Clothing/OuterClothing/Hardsuits/CrimsonLily/scaf.rsi
  - type: ToggleableClothing
    clothingPrototype: ClothingHeadHelmetHardsuitAgentCrimsonLily

- type: entity
  parent: ClothingHeadHardsuitWithLightBase
  id: ClothingHeadHelmetHardsuitAgentCrimsonLily
  categories: [ HideSpawnMenu ]
  name: crimson lily agent hardsuit helmet
  description: With a hardsuit helmet like that, you can catch a bullet in the forehead!
  suffix: ACL
  components:
  - type: Sprite
    sprite: DarkStation/MainGame/Clothing/OuterClothing/Hardsuits/CrimsonLily/helmet.rsi
  - type: Clothing
    sprite: DarkStation/MainGame/Clothing/OuterClothing/Hardsuits/CrimsonLily/helmet.rsi
  - type: PointLight
    color: "#ffadc6"
    radius: 7
  - type: PressureProtection
    highPressureMultiplier: 0.60
    lowPressureMultiplier: 5500
  - type: Armor
    modifiers:
      coefficients:
        Blunt: 0.9
        Slash: 0.9
        Piercing: 0.9
        Heat: 0.9
        Radiation: 0.90
        Caustic: 0.95
      securePartTypes:
        Head: 0.5
# Weapon

- type: entity
  name: LPP-12
  parent: WeaponPulsePistol
  id: StationACLWeaponPulsePistol
  description: A limited 12 series pulse pistol made specifically for Finance Department agents who are left on station for small but self-defense. The difference from the standard model pulse pistol is weaker damage. But that's okay! It's guaranteed durability!
  components:
  - type: Sprite
    sprite: Objects/Weapons/Guns/Battery/pulse_pistol.rsi
    layers:
    - state: base
      map: [ "enum.GunVisualLayers.Base" ]
    - state: mag-unshaded-4
      map: [ "enum.GunVisualLayers.MagUnshaded" ]
      shader: unshaded
  - type: Clothing
    sprite: Objects/Weapons/Guns/Battery/pulse_pistol.rsi
  - type: Gun
    selectedMode: SemiAuto
    availableModes:
    - SemiAuto
    soundGunshot:
      path: /Audio/Weapons/Guns/Gunshots/laser_cannon.ogg
  - type: HitscanBatteryAmmoProvider
    proto: StationACLPulse
    fireCost: 150
  - type: Battery
    maxCharge: 2250
    startingCharge: 2250

- type: hitscan
  id: StationACLPulse
  damage:
    types:
      Heat: 10
  muzzleFlash:
    sprite: Objects/Weapons/Guns/Projectiles/projectiles.rsi
    state: muzzle_omni
  travelFlash:
    sprite: Objects/Weapons/Guns/Projectiles/projectiles.rsi
    state: beam_omni
  impactFlash:
    sprite: Objects/Weapons/Guns/Projectiles/projectiles.rsi
    state: impact_omni

# Storage
- type: entity
  id: ClothingBackpackAgentCrimsonLily
  parent: ClothingBackpackHolding
  name: crimson lily agent backpack
  suffix: ACL
  components:
  - type: Storage
    maxItemSize: Huge
    grid:
    - 0,0,9,6

# PDA and Card

- type: entity
  parent: IDCardStandard
  id: AgentCrimsonLilyIDCard
  name: crimson lily agent ID card
  suffix: ACL
  components:
  - type: Sprite
    layers:
    - state: centcom
    - state: idcentcom
  - type: PresetIdCard
    job: AgentCrimsonLily

- type: entity
  parent: DeathsquadPDA
  id: AgentCrimsonLilyPDA
  name: crimson lily agent PDA
  description: Smells like money and bureaucracy.
  suffix: ACL
  components:
  - type: Sprite
    sprite: DarkStation/MainGame/Objects/Devices/pda.rsi
    layers:
      - map: [ "enum.PdaVisualLayers.Base" ]
        state: "pda-ABL"
      - state: "light_overlay"
        map: [ "enum.PdaVisualLayers.Flashlight" ]
        shader: "unshaded"
        visible: false
      - state: "id_overlay"
        map: [ "enum.PdaVisualLayers.IdLight" ]
        shader: "unshaded"
        visible: false
  - type: Pda
    id: AgentCrimsonLilyIDCard
    state: pda-ABL
  - type: Appearance
    appearanceDataInit:
     enum.PdaVisuals.PdaType:
       !type:String
       pda-ABL
  - type: Icon
    sprite: DarkStation/MainGame/Objects/Devices/pda.rsi
    state: pda-ABL
# Special

- type: entity
  parent: BoxCardboard
  id: BoxAgentCrimsonLily
  name: acl bureaucratic kit
  suffix: ACL
  description: Agent crimson lily bureaucratic kit.
  components:
  - type: StorageFill
    contents:
    - id: RubberStampApproved
    - id: RubberStampDenied
    - id: RubberStampFinanceDepACL
  - type: Sprite
    layers:
    - state: internals
    - state: emergencytank

- type: entity
  parent: EncryptionKey
  id: EncryptionKeyCrimsonLily
  name: crimson lily agent encryption key
  description: An encryption key used by the business guys.
  components:
  - type: EncryptionKey
    channels:
    - Supply
    - CrimsonLily
    defaultChannel: CrimsonLily
  - type: Sprite
    layers:
    - state: crypt_blue
    - state: nano_label

# Spawner
- type: entity
  id: SpawnPointAgentCrimsonLily
  parent: SpawnPointJobBase
  name: Spawner AgentCrimsonLily
  components:
  - type: SpawnPoint
    job_id: AgentCrimsonLily
  - type: Sprite
    layers:
    - state: green
    - state: dark_AgentCrimsonLily
